import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import re
import warnings
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

warnings.filterwarnings('ignore')

# --- CONFIGURATION ---
SCRIPT_DIR = Path(__file__).parent.resolve()
DB_PATH = SCRIPT_DIR / "gitgalaxy_master_v2.db" # Updated to your v2 DB
OUTPUT_DIR = SCRIPT_DIR / "archetype_predictive_scatters"

def generate_predictive_plots():
    OUTPUT_DIR.mkdir(exist_ok=True)
    
    print(f"📡 Connecting to database: {DB_PATH}...")
    if not DB_PATH.exists():
        print("❌ Error: Database not found!")
        return
        
    conn = sqlite3.connect(DB_PATH)
    # Load files with code, ignoring purely text/doc files
    df = pd.read_sql_query("SELECT * FROM galactic_census WHERE coding_loc > 0", conn)
    conn.close()

    print(f"📦 Loaded {len(df):,} total files with executable code.")

    # 1. PREP THE PREDICTORS (X)
    risk_cols = [c for c in df.columns if c.startswith('risk_')]
    df[risk_cols] = df[risk_cols].fillna(0.0)
    df['archetype'] = df['archetype'].fillna("Unknown")
    
    # Grab the top 16 most populated archetypes
    top_archetypes = df['archetype'].value_counts().head(16).index.tolist()
    archetypes = sorted([a for a in top_archetypes if "Cluster" in a])

    if not archetypes:
        print("❌ Error: No archetypes found containing the word 'Cluster'.")
        return

    print(f"\n📊 Running Multiple Linear Regression for {len(archetypes)} Archetypes...")
    print("-" * 60)
    
    plots_generated = 0
    db_columns = df.columns.tolist()

    for arch in archetypes:
        # Extract cluster number
        match = re.search(r'Cluster (\d+)', arch)
        if not match:
            continue
            
        cluster_num = match.group(1)
        
        # ---> THE FIX: Match the actual DB column names generated by your builder <---
        col_name = next((c for c in db_columns if c.startswith(f"arch_cluster_{cluster_num}")), None)
        
        if not col_name: 
            print(f"⚠️ Skipped '{arch}': Could not find column '{col_name}'.")
            continue
            
        # Isolate the files that belong to this specific cluster
        subset = df[df['archetype'] == arch].copy()
        
        if len(subset) < 20: # Bumped up min samples to 20 for multiple regression
            print(f"⚠️ Skipped '{arch}': Not enough files ({len(subset)}) for multivariate regression.")
            continue
            
        # 2. DEFINE X (All Risks) and y (Actual Z-Score Drift)
        X = subset[risk_cols]
        y_actual = subset[col_name].fillna(0.0)
        
        if np.std(y_actual) == 0: 
            print(f"⚠️ Skipped '{arch}': No variance in Euclidean drift.")
            continue
            
        # Filter out risk columns that have zero variance in this subset (they break the math)
        valid_risk_cols = [col for col in risk_cols if np.std(X[col]) > 0]
        if not valid_risk_cols:
            print(f"⚠️ Skipped '{arch}': No variance in any risk exposures.")
            continue
            
        X = X[valid_risk_cols]
            
        # 3. BUILD THE PREDICTIVE MODEL
        model = LinearRegression()
        model.fit(X, y_actual)
        y_pred = model.predict(X)
        
        # Calculate R-squared (How much of the drift is explained by the risk combo?)
        r2 = r2_score(y_actual, y_pred)
        
        # Get the top 3 most impactful risks in this specific equation
        coefficients = list(zip(valid_risk_cols, model.coef_))
        coefficients.sort(key=lambda item: abs(item[1]), reverse=True)
        top_equation = " + ".join([f"({coef:.3f} * {risk.replace('risk_', '')})" for risk, coef in coefficients[:3]])
        
        # 4. PLOT ACTUAL VS PREDICTED
        sns.set_theme(style="darkgrid")
        plt.figure(figsize=(10, 8))
        
        # Downsample for faster plotting if huge
        if len(subset) > 5000:
            plot_idx = np.random.choice(len(y_actual), 5000, replace=False)
            y_actual_plot, y_pred_plot = y_actual.iloc[plot_idx], y_pred[plot_idx]
        else:
            y_actual_plot, y_pred_plot = y_actual, y_pred
            
        # Scatter of predictions
        sns.scatterplot(
            x=y_actual_plot, 
            y=y_pred_plot, 
            alpha=0.4, 
            color='#3498db', 
            edgecolor='none',
            s=30
        )
        
        # Draw the "Perfect Prediction" diagonal line (y = x)
        min_val = min(y_actual_plot.min(), y_pred_plot.min())
        max_val = max(y_actual_plot.max(), y_pred_plot.max())
        plt.plot([min_val, max_val], [min_val, max_val], color='#e74c3c', linestyle='--', linewidth=2, label='Perfect Prediction (y=x)')
        
        # Formatting
        clean_title = arch[:60] + "..." if len(arch) > 60 else arch
        plt.title(f"Predicting Architectural Drift via Risk Exposures\n{clean_title}", fontsize=14, weight='bold', pad=20)
        plt.xlabel("Actual Z-Score / Euclidean Drift", fontsize=12)
        plt.ylabel("Predicted Drift (From Risk Combo)", fontsize=12)
        
        # Add a text box with the R^2 and the top driving equation
        stats_text = f"Variance Explained ($R^2$): {r2:.3f}\n\nTop Predictors (Combo):\n{top_equation}"
        plt.text(0.05, 0.95, stats_text, transform=plt.gca().transAxes, fontsize=10,
                 verticalalignment='top', bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))
        
        plt.legend(loc='lower right')
        plt.tight_layout()
        
        # 5. SAVE
        safe_arch_name = re.sub(r'[^a-z0-9]+', '_', arch.split(':')[0].lower()).strip('_')
        out_file = OUTPUT_DIR / f"{safe_arch_name}_predictive_scatter.png"
        plt.savefig(out_file, dpi=150, bbox_inches='tight')
        plt.close()
        
        print(f"✅ Exported: {out_file.name} (R² = {r2:.3f})")
        plots_generated += 1

    if plots_generated > 0:
        print(f"\n🚀 SUCCESS: {plots_generated} predictive plots saved to '{OUTPUT_DIR.name}'.")
    else:
        print("\n❌ FAILURE: No plots generated. Check warnings above.")

if __name__ == "__main__":
    generate_predictive_plots()